mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'lens.l.google.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

script:
  shortcuts:
    quic: network == 'udp' and (dst_port == 443 or dst_port == 4483 or dst_port == 9305)
    BilibiliUdp: network == "udp" and match_provider("BiliBili")
    
rules:
  - DOMAIN,r2s.asuka.ga,DIRECT
  - SCRIPT,quic,REJECT
  - SCRIPT,BilibiliUdp,REJECT
