on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: false
  schedule:
    - cron: "0 18 */1 * *"

name: rules
jobs:
  sync:
    runs-on: ubuntu-22.04
    env:
      TZ: Europe/Busingen
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Sync
        run: |
          sudo apt-get install -y nodejs jsonlint
          chmod +x run.sh
          ./run.sh --all

      - name: Commit Changes
        run: |
          echo "update on $(date)" >> .github/log.txt
          git config --local user.name "github-action[bot]"
          git config --local user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -am "update on $(date)"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Publish
        run: |
          mv adblock clash seo iptv bpc clearurls userscripts index

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: index
